---
# tasks file for pre-flight_role
# Dependency install prior to application deployment on Server.


# Subscription Manager
- name: Register with Subscription
  redhat_subscription:
    state: present
    username: "{{sub_username}}"
    password: "{{sub_pass}}"
    auto_attach: true
    force_register: yes
  become: yes
  no_log: true
  when: ansible_facts[‘distribution’] == RedHat
 
# Enable SCL Repos through Sub manager
- name: SCL Enable
  rhsm_repository:
    name: rhel-server-rhscl-7-rpms
    state: present
  become: yes
  when: ansible_facts[‘distribution’] == RedHat

 #Enable Optional Repos through Sub manager

- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
    repo_gpgcheck: no
  become: yes

- name: Optional Repos Enable
  rhsm_repository:
    name: rhel-7-server-optional-rpms
    state: present   
  become: yes
  when: ansible_facts[‘distribution’] == RedHat 

- name: Download Python Pip bootstrap
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: ~/
  become: yes

- name: Install Pip
  command: python ~/get-pip.py
  become: yes


- name: Install Crypto Package
  pip:
    name: cryptography
    state: present
  become: yes


- name: Install Python Postgres Pack
  pip:
    name: psycopg2-binary
    state: present
  become: yes

- name: Install PHP Modules (NextCloud Prep)
  yum:
    name:
      - rh-php73-php
      - rh-php73-php-cli   
      - rh-php73-php-fpm
      - rh-php73-php-curl
      - rh-php73-php-pgsql
      - rh-php73-php-json
      - rh-php73-php-bz2
      - rh-php73-php-xml
      - rh-php73-php-ldap
      - rh-php73-php-gd
      - rh-php73-php-opcache
      - rh-php73-php-common
      - rh-php73-php-mbstring
      - rh-php73-php-gmp
      - rh-php73-php-intl
      - rh-php73-php-zip
      - rh-php73-php-posix
    state: present
  become: yes
      
- name: Install Ruby Dependancies (Redmine Prep)
  yum:
    name:
      - pygpgme
      - gcc
      - libyaml-devel
      - ImageMagick
      - ImageMagick-devel
      - rpm-build 
      - zlib-devel
      - zlib
      - autoconf 
      - automake 
      - bison 
      - curl
      - gcc-c++ 
      - libffi-devel 
      - libtool 
      - readline-devel 
      - sqlite-devel 
      - openssl-devel
      - postgresql-devel
      - libcurl-devel
      #####SELinux Dependency####
      - policycoreutils-python-2.5-34.el7
    state: present
  become: yes



